# [numpy.add](https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html)
* 用例:    
**numpy.add**(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'add'>

* 功能:     
两个数组对应位置的元素求和。

* 参数   

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| x1,x2 | 数组型变量 | 用于求和的数组。如果`x1.shape != x2.shape`，它们必须扩充到同样的维度（此维度也等于返回结果的维度）。 |
| out | n维数组，None，或者多维数组组成的元组，可选参数 | 指定结果存储的位置。若提供此参数，其必须与输入数组扩充后的维度保持一致。<br>如果不提供此参数或者此参数为None，返回一个新建的数组。若此参数为元组，其长度和输出值的个数保持一致。</br> |
| where | 数组型变量，可选参数 | 此参数用默认值即可。 |

* 返回值

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| add | n维数组或者是标量 | 将x1和x2中对应位置的元素相加。如果x1和x2为标量，那么返回值也为标量。 |   

* 备注
***
此函数的运算结果和`x1 + x2`一致。  

* 示例:

In [1]:
import numpy as np
print('标量相加的结果：{}'.format(np.add(1.0, 4.0)))
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
# 会将x2复制三行变为3*3二维数组再相加
print('向量相加的结果：\n{}'.format(np.add(x1, x2)))

标量相加的结果：5.0
向量相加的结果：
[[ 0.  2.  4.]
 [ 3.  5.  7.]
 [ 6.  8. 10.]]
