# [numpy.arange](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.arange.html)
* 用例:    
**numpy.arange**([start, ]stop, [step, ]dtype=None)

* 功能:     
返回给定区间范围内间隔均匀的数值。   
生成半闭区间范围`[start, stop)`内的数值（换句话说，取值范围包括区间的起始值而不包括区间的终止值）。对于整数参数而言，这个函数和Python内置函数`range`的功能是相同的。不同的是，`np.arange`的返回值为n维数组，而`range`的返回值为列表。     
当使用非整数步长时，例如0.1，结果往往不一致。在这种情况下更推荐使用`linspace`。

* 参数   

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| start | 数值型，可选参数 | 区间的起始值。区间包含此值，默认值为0 |
| stop | 数值型 | 区间的终止值。区间不包含此值，除非在某些情况下，step不是整数，并且浮点数的舍入会影响最后一个数的取值。 |
| step | 数值型，可选参数 | 两个数字之间的间隔。对于任何输出，此参数为相邻两个值之间的距离（`out[i+1] - out[i]`）。默认步长值为1。<br>如果指定步长值就必须指定区间的起始值start。</br> |
| dtype | 数值类型 | 输出数组的数值类型。如果不给定`dtype`参数，函数通过其他的输入参数推断返回值的类型。 |

* 返回值

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| arange | n维数组 | 均匀间隔数字组成的数组。对于浮点型参数，返回数组的长度为`ceil((stop - start)/step)`。由于浮点溢出，此规则可能导致输出的最后一个元素大于stop。 |   

* 示例:

In [1]:
import numpy as np
np.arange(3)

array([0, 1, 2])

In [2]:
np.arange(3.0)

array([0., 1., 2.])

In [3]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [4]:
np.arange(3, 7, 2)

array([3, 5])