# [numpy.argmax](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.argmax.html)
* 用例:        
 **numpy.argmax**(a, axis=None, out=None)

* 功能:     
返回数组沿着某一条轴最大值的索引。

* 参数   

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| a | 数组型变量 | 输入数据。 |
| axis | 整型，可选参数 | 默认情况下，会先将数组变为一维数组，然后求最大值的索引。否则沿着指定轴计算最大值索引。 |
| out | 数组，可选参数 | 若提供此参数，结果将保存到这个数组中。必须为其指定合适的形状和数值类型。 |

* 返回值

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| index_array | n维数组或整数 | 数组中的索引。其维度与a.shape中沿轴方向的大小一致。 |  

* 备注       
若出现多个最大值，则返回最大值第一次出现位置的索引。 

* 示例:    

In [1]:
import numpy as np
a = np.arange(6).reshape(2,3)
print('a数组：\n{}'.format(a))
print('a数组中最大值的索引：{}'.format(np.argmax(a)))
print('a数组沿列方向最大值的索引：{}'.format(np.argmax(a, axis=0)))
print('a数组沿行方向最大值的索引：{}'.format(np.argmax(a, axis=1)))
b = np.arange(6)
b[1] = 5
print('b数组：\n{}'.format(b))
print('b数组最大值的索引：{}'.format(np.argmax(b)))  # 仅仅返回5第一次出现的位置

a数组：
[[0 1 2]
 [3 4 5]]
a数组中最大值的索引：5
a数组沿列方向最大值的索引：[1 1 1]
a数组沿行方向最大值的索引：[2 2]
b数组：
[0 5 2 3 4 5]
b数组最大值的索引：1
