# [numpy.concatenate](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.concatenate.html)
* 用例:    
**numpy.concatenate**((a1, a2, ...), axis=0, out=None)

* 功能:     
沿着指定的轴拼接一系列数组。     

* 参数   

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| a1,a2,... | 数组组成的序列 | 这些数组除了拼接方向（默认为y轴方向）的维度以外，其余维度必须保持一致 |
| axis | 整型，可选参数 | 数组拼接所沿的轴方向。如果axis是None，所有数组在拼接前都会被转为1维。此参数的默认值为0。 |
| out | n维数组，可选参数 | 若提供此参数，则指定计算结果的存储位置。若指定out参数，其维度必须和拼接后返回数组的维度保持一致。 |

* 返回值

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| res | n维数组 | 拼接后返回的数组 |   

* 备注
***
当一个或者多个数组被拼接时，这个函数会返回掩码数组而不是多维数组，但是输入数组的掩码不被保留。当用户期望输入数组为掩码数组时，请使用掩码数组模块中的`ma.concatenate`函数。   

* 示例:

In [1]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print('纵向拼接的结果为：\n{}'.format(np.concatenate((a, b), axis=0)))
print('a和b的转置横向拼接的结果为：\n{}'.format(np.concatenate((a, b.T), axis=1)))
print('将两个数组拉伸为1维后进行拼接的结果为：{}'.format(np.concatenate((a, b), axis=None)))

纵向拼接的结果为：
[[1 2]
 [3 4]
 [5 6]]
a和b的转置横向拼接的结果为：
[[1 2 5]
 [3 4 6]]
将两个数组拉伸为1维后进行拼接的结果为：[1 2 3 4 5 6]


这个函数不会为输入数组保留掩码

In [2]:
a = np.ma.arange(3)
a[1] = np.ma.masked
b = np.arange(2, 5)
a

masked_array(data=[0, --, 2],
             mask=[False,  True, False],
       fill_value=999999)

In [3]:
b

array([2, 3, 4])

In [4]:
np.concatenate([a, b])

masked_array(data=[0, 1, 2, 2, 3, 4],
             mask=False,
       fill_value=999999)

In [5]:
np.ma.concatenate([a, b])

masked_array(data=[0, --, 2, 2, 3, 4],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)