# [numpy.random.randint](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.randint.html)
* 用例:   
**numpy.random.randint**(low, high=None, size=None, dtype='l')   

* 功能:    
返回low(包括)到high(不包括)之间的随机整数，即`[low, high)`。    
从半开区间`[low, high)`中返回满足离散均匀分布的随机整数，这些数据需符合函数指定的数据类型。如果未指定high（即采用默认值None），那么结果将落到区间`[0, low)`。     
* 参数   

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| low | 整数型数据 | 从分布中抽取的最小(有符号)整数(当`high=None`时，此参数比取值空间最大的整数大1) |
| high | 整数型数据，可选参数 | 如果提供此参数，则其比取值空间最大的整数大1(如果`high=None`，请参见上面的解释) |
| size | 整数或整数组成的元组，可选参数 | 用于指定返回值的维度，如果给定的维度是`(m, n, k)`，<br>那么将会抽取`m * n * k`个样本。此参数的默认值为None，在这种情况下仅返回一个值</br> |
| dtype | 数据类型，可选参数 | 此参数用于指定返回值的数据类型。所有的数据类型由它们的名字指定，例如：‘int64’,‘int’等等，<br>所以不可以指定字节顺序，并且不同的环境下数值的精度有可能不相同。此参数的默认值为‘np.int’。</br> |    

* 返回值

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| out | 整数或整数组成的n维数组 | 若指定size，则返回指定大小的服从离散均匀分布的随机整数。若size未指定，则会返回指定范围内的一个随机整数 |  

* 示例

In [1]:
import numpy as np
print(np.random.randint(2, size=10))
print(np.random.randint(1, size=10))

[1 0 0 1 1 1 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


生成[0, 4]之间2*4大小的数组

In [2]:
np.random.randint(0, 5, size=(2, 4))

array([[0, 0, 1, 4],
       [3, 4, 2, 4]])