# [numpy.tril](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tril.html#numpy.tril)
* 用例:    
 **numpy.tril**(m, k=0)

* 功能:     
返回数组的下三角部分。     
数组拷贝之后，将其第k条对角线上方的元素全部置零。

* 参数   

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| m | 形状为(M,N)的数组型变量 | 输入数组。 |
| k | 整型，可选参数 | 第k条对角线上方的元素全部置零。k=0（默认值），为主对角线，k<0为主对角线左下方，k>0为主对角线右上方。 |

* 返回值

| 变量名 | 数据类型 | 功能 |
|:---:|:---:|:---:|
| tril | 形状为(M,N)的二维数组 | m的下三角，其形状和数值类型和m一致。 |  

* 示例:    

In [1]:
import numpy as np
print('下三角矩阵：\n{}'.format(np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)))

下三角矩阵：
[[ 0  0  0]
 [ 4  0  0]
 [ 7  8  0]
 [10 11 12]]
