# [numpy.triu](https://docs.scipy.org/doc/numpy/reference/generated/numpy.triu.html#numpy.triu)
* 用例:    
 **numpy.triu**(m, k=0)

* 功能:     
返回数组的上三角部分。     
对矩阵进行拷贝，并将第k条对角线下方的元素全部置零。     
关于数组下三角的相关知识[参见文档](https://blog.csdn.net/wzy628810/article/details/104043768)。

* 示例:    

In [1]:
import numpy as np
print('数组的上三角部分：\n{}'.format(np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)))

数组的上三角部分：
[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]]
